### ISSUE TITLE
Building issue: "region `iram1_0_seg' overflowed"

### ISSUE THREAD

**Issue by wally666** [devbis/st7789_mpy#1]
Hi

I have working dev toolchain for Esp8266 configured in Docker. When I add your module:

`
git clone https://github.com/devbis/st7789_mpy.git /st7789_mpy

make USER_C_MODULES=/st7789_mpy all
`

I get compilation error "**region `iram1_0_seg' overflowed by 1368 bytes**":

`
...
CC /st7789_mpy/st7789/st7789.c
CC ../../lib/axtls/ssl/asn1.c
CC ../../lib/axtls/ssl/loader.c
CC ../../lib/axtls/ssl/tls1.c
CC ../../lib/axtls/ssl/tls1_svr.c
CC ../../lib/axtls/ssl/tls1_clnt.c
CC ../../lib/axtls/ssl/x509.c
CC ../../lib/axtls/crypto/aes.c
CC ../../lib/axtls/crypto/bigint.c
CC ../../lib/axtls/crypto/crypto_misc.c
CC ../../lib/axtls/crypto/hmac.c
CC ../../lib/axtls/crypto/md5.c
CC ../../lib/axtls/crypto/rsa.c
CC ../../lib/axtls/crypto/sha1.c
CC ../../extmod/modbtree.c
CC ../../lib/berkeley-db-1.xx/btree/bt_close.c
CC ../../lib/berkeley-db-1.xx/btree/bt_conv.c
CC ../../lib/berkeley-db-1.xx/btree/bt_debug.c
CC ../../lib/berkeley-db-1.xx/btree/bt_delete.c
CC ../../lib/berkeley-db-1.xx/btree/bt_get.c
CC ../../lib/berkeley-db-1.xx/btree/bt_open.c
CC ../../lib/berkeley-db-1.xx/btree/bt_overflow.c
CC ../../lib/berkeley-db-1.xx/btree/bt_page.c
CC ../../lib/berkeley-db-1.xx/btree/bt_put.c
CC ../../lib/berkeley-db-1.xx/btree/bt_search.c
CC ../../lib/berkeley-db-1.xx/btree/bt_seq.c
CC ../../lib/berkeley-db-1.xx/btree/bt_split.c
CC ../../lib/berkeley-db-1.xx/btree/bt_utils.c
CC ../../lib/berkeley-db-1.xx/mpool/mpool.c
AS gchelper.s
CC ../../extmod/modlwip.c
CC ../../extmod/modonewire.c
CC ../../lib/libc/string0.c
CC ../../lib/libm/math.c
CC ../../lib/libm/fmodf.c
CC ../../lib/libm/nearbyintf.c
CC ../../lib/libm/ef_sqrt.c
CC ../../lib/libm/kf_rem_pio2.c
CC ../../lib/libm/kf_sin.c
CC ../../lib/libm/kf_cos.c
CC ../../lib/libm/kf_tan.c
CC ../../lib/libm/ef_rem_pio2.c
CC ../../lib/libm/sf_sin.c
CC ../../lib/libm/sf_cos.c
CC ../../lib/libm/sf_tan.c
CC ../../lib/libm/sf_frexp.c
CC ../../lib/libm/sf_modf.c
CC ../../lib/libm/sf_ldexp.c
CC ../../lib/libm/asinfacosf.c
CC ../../lib/libm/atanf.c
CC ../../lib/libm/atan2f.c
CC ../../lib/mp-readline/readline.c
CC ../../lib/netutils/netutils.c
CC ../../lib/timeutils/timeutils.c
CC ../../lib/utils/pyexec.c
CC ../../lib/utils/interrupt_char.c
CC ../../lib/utils/sys_stdio_mphal.c
CC ../../lib/oofatfs/ff.c
CC ../../lib/oofatfs/ffunicode.c
CC ../../drivers/bus/softspi.c
CC ../../drivers/dht/dht.c
LINK build/firmware.elf

xtensa-lx106-elf-ld: build/firmware.elf section `.text' will not fit in region `iram1_0_seg'

xtensa-lx106-elf-ld: region `iram1_0_seg' overflowed by 1368 bytes

make: *** [build/firmware.elf] Error 1
`

Have you ever seen similar problem before?

**Comment by devbis** [comment]
Hi!
Yes, this problem is described in the Troubleshooting section of the readme:

https://github.com/devbis/st7789_mpy/issues#troubleshooting

Just put the module to irom section.

**Comment by wally666** [comment]
Pardom me. I've no idea how I missed the description.
Of corse it helped!

Thanks :)
