### ISSUE TITLE
compile issue - ESP IDF does not match the supported version

### ISSUE THREAD

**Issue by ds2k5** [devbis/st7789_mpy#16]
Hello,
did not get the module compiled.
Hardware: TTGO ESP32 with 1.4" Display

1. git clone https://github.com/micropython/micropython
2. git clone https://github.com/devbis/st7789_mpy.git
3. git clone https://github.com/espressif/esp-idf.git 
4. cd esp-idf && git submodule update --init --recursive && sudo ./install.sh && cd ..
5. install xtensa-esp32-elf-gcc
6. cd micropython/ports/esp32
7.  make USER_C_MODULES=../../../st7789_mpy/ all

$ make USER_C_MODULES=../../../st7789_mpy/ all 
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Including User C Module from ../../../st7789_mpy//st7789
** WARNING **
The git hash of ESP IDF does not match the supported version
The build may complete and the firmware may work but it is not guaranteed
ESP IDF path:       /home/developer/Downloads/esp-idf
Current git hash:   8bc19ba893e5544d571a753d82b44a84799b94b1
Supported git hash (v3.3): 9e70825d1e1cbf7988cf36981774300066580ea7
Supported git hash (v4.0) (experimental): 4c81978a3e2220674a432a588292a4c860eef27b
GEN build-GENERIC/sdkconfig.h
Traceback (most recent call last):
  File "/home/developer/Downloads/esp-idf/tools/kconfig_new/confgen.py", line 31, in <module>
    from future.utils import iteritems
ModuleNotFoundError: No module named 'future'
make: *** [Makefile:401: build-GENERIC/sdkconfig.h] Error 1

What did I wrong ?

------------

when run install.sh in user context.... got this

$ make v=1 USER_C_MODULES=../../../st7789_mpy/ all
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Including User C Module from ../../../st7789_mpy//st7789
** WARNING **
The git hash of ESP IDF does not match the supported version
The build may complete and the firmware may work but it is not guaranteed
ESP IDF path:       /home/developer/Downloads/esp-idf
Current git hash:   8bc19ba893e5544d571a753d82b44a84799b94b1
Supported git hash (v3.3): 9e70825d1e1cbf7988cf36981774300066580ea7
Supported git hash (v4.0) (experimental): 4c81978a3e2220674a432a588292a4c860eef27b
GEN build-GENERIC/sdkconfig.h
/home/developer/Downloads/esp-idf/Kconfig:14: warning: IDF_ENV_FPGA has 'option env="IDF_ENV_FPGA"', but the environment variable IDF_ENV_FPGA is not set
Traceback (most recent call last):
  File "/home/developer/Downloads/esp-idf/tools/kconfig_new/confgen.py", line 641, in <module>
    main()
  File "/home/developer/Downloads/esp-idf/tools/kconfig_new/confgen.py", line 261, in main
    config = kconfiglib.Kconfig(args.kconfig)
  File "/home/developer/Downloads/esp-idf/tools/kconfig_new/kconfiglib.py", line 947, in __init__
    self._init(filename, warn, warn_to_stderr, encoding)
  File "/home/developer/Downloads/esp-idf/tools/kconfig_new/kconfiglib.py", line 1085, in _init
    self._parse_block(None, self.top_node, self.top_node).next = None
  File "/home/developer/Downloads/esp-idf/tools/kconfig_new/kconfiglib.py", line 2970, in _parse_block
    raise KconfigError(
kconfiglib.KconfigError: /home/developer/Downloads/esp-idf/Kconfig:173: '$COMPONENT_KCONFIGS_PROJBUILD_SOURCE_FILE' not found (in 'source "$COMPONENT_KCONFIGS_PROJBUILD_SOURCE_FILE"'). Check that environment variables are set correctly (e.g. $srctree, which is unset or blank). Also note that unset environment variables expand to the empty string.
make: *** [Makefile:401: build-GENERIC/sdkconfig.h] Error 1

**Comment by devbis** [comment]
It is not an issue in the driver. You should read the instruction in MicroPython docs how to compile MP for ESP32.

https://github.com/micropython/micropython/tree/master/ports/esp32
