### ISSUE TITLE
Can't build on ESP8266

### ISSUE THREAD

**Issue by w4rum** [devbis/st7789_mpy#23]
The README contains performance measurements for the ESP8266 and also states how to build MicroPython with this module for the ESP8266. However, I can't get the current version of MicroPython to include this module when building.

I'm using the ["recommended"](https://github.com/micropython/micropython/blob/master/ports/esp8266/README.md) way to build for ESP8266, which is using docker:
```sh
~/Downloads/micropython/ports/esp8266
> docker run --rm -v $HOME:$HOME -u (id -u) -w $PWD larsks/esp-open-sdk make USER_C_MODULES=../../../st7789_mpy/st7789/micropython.cmake all
```
This builds fine but produces exactly the same image as without the `USER_C_MODULES` argument. When flashing the produced image, `import st7789` does not work.

When looking over the [Makefile](https://github.com/micropython/micropython/blob/master/ports/esp8266/Makefile) in `micropython/ports/esp8266`, I noticed that neither `USER_C_MODULES` nor `cmake` is referenced at all. I also couldn't find anything else on how to include external modules in an ESP8266 build.

Am I missing something here?

**Comment by devbis** [comment]
Unfortunately, I don't have an opportunity to run the build and fix it. 
You can try this fork https://github.com/russhughes/st7789_mpy maybe it would work in your case.

**Comment by w4rum** [comment]
After some help from the guys over on the Micropython repo I figured out that the problem was on my end. I somehow fucked up my working copy of the module. The build instructions in the readme work (minus the new recommended docker-based build). Sorry for the inconvenience.

See: https://github.com/micropython/micropython/issues/8655
