### ISSUE TITLE
Driver not working correctly with display 135 x 240 pixels

### ISSUE THREAD

**Issue by nobodyman1** [devbis/st7789_mpy#3]
I want to use the driver with this board: [https://github.com/Xinyuan-LilyGO/TTGO-T-Display](https://github.com/Xinyuan-LilyGO/TTGO-T-Display)
The display is 1.14 inch and has 135 x 240 pixels.
I have to use software SPI and a dummy pin (25) for MISO.
```
from machine import Pin, SPI
import st7789
spi = SPI(-1, baudrate=40000000, polarity=1, phase=0, sck=Pin(18), mosi=Pin(19), miso=Pin(25))
display = st7789.ST7789(spi, 135, 240, reset=Pin(23, Pin.OUT), dc=Pin(16, Pin.OUT), cs=Pin(5, Pin.OUT))
display.init()
tftbl = Pin(4, Pin.OUT)
tftbl.on()
display.fill(st7789.WHITE)
```
The display is switched on but the white color is not written on the complete display.
The example code for the board uses an Arduino driver ([https://github.com/Bodmer/TFT_eSPI](https://github.com/Bodmer/TFT_eSPI)) which works perfectly.
It seems the driver needs an offset in x and y direction (CGRAM_OFFSET).

**Comment by devbis** [comment]
Yes, it seems the library needs offsets for other sizes. 
But I don't have the TTGO-T board, so it would be difficult to test the results. 
Could you please add the required changed and make a pull request?

**Comment by devbis** [comment]
It seems, there is a fork that is intended to work with your display.

https://github.com/mmone/st7789_mpy/commit/0590b495a6f7be6a9e3b7ccc66d252d4505ac087

Can you please check it works with your display, and then I will add support for it

**Comment by nobodyman1** [comment]
I created a fork and implemented the changes. It works!

**Comment by devbis** [comment]
Thanks for the pull request. Unfortunately, it breaks the original 240x240 display.

I added changes that allow using both 240x240 and 135x240 displays. 
Could you please test it on your LCD?

**Comment by nobodyman1** [comment]
Great, it works with 135x240 pixels! Thank you very much.

**Comment by dvarrel** [comment]
Great Job, thank you !
