### ISSUE TITLE
error compile module

### ISSUE THREAD

**Issue by dvarrel** [devbis/st7789_mpy#5]
hello,
i try to compile your module with esp32, and this is the reported error:
`dam@dvarrel-pc:~/esp/micropython/ports/esp32$ make USER_C_MODULES=../../../st7789_mpy/ all
Use make V=1 or set BUILD_VERBOSE in your environment to increase build verbosity.
Including User C Module from ../../../st7789_mpy//st7789
Building with ESP IDF v3
CC ../../../st7789_mpy/st7789/st7789.c
In file included from ../../../st7789_mpy/st7789/st7789.c:27:0:
../../../st7789_mpy/st7789/st7789.c:469:19: error: 'MP_QSTR_blit_buffer' undeclared here (not in a function)

thank you
`

**Comment by elektroid** [comment]
I have the same issue. As a temporary solution it does compile if you `git checkout dfa1346bd3954260c602ee5cdce12b5f5dddb124`

**Comment by dvarrel** [comment]
it's ok. I haven't delete the build-GENERIC directory
